databases:
  - name: celery_proj
    databaseName: celery_proj
    user: celery_proj
    plan: free

services:
  - type: web
    name: celery_proj
    plan: free
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: celery_proj
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
  # - type: worker
  #   name: queue
  #   region: ohio
  #   env: python
  #   buildCommand: "pip install -r requirements.txt"
  #   startCommand: "celery --app tasks worker --loglevel info --concurrency 4"
  #   autoDeploy: false
  #   envVars:
  #     - key: CELERY_BROKER_URL
  #       fromService:
  #         name: celery-redis
  #         type: redis
  #         property: connectionString
  # - type: web
  #   name: flower
  #   region: ohio
  #   plan: free
  #   env: python
  #   buildCommand: "pip install -r requirements.txt"
  #   startCommand: "celery flower --app tasks --loglevel info"
  #   autoDeploy: false
  #   envVars:
  #     - key: CELERY_BROKER_URL
  #       fromService:
  #         type: redis
  #         name: celery-redis
  #         property: connectionString
  # - type: redis
  #   name: celery-redis
  #   region: ohio
  #   plan: free
  #   maxmemoryPolicy: noeviction # recommended policy for queues
  #   ipAllowList: [] # only allow internal connections